--============ Copyright © 2017, Planimeter, All rights reserved. ============--
--
-- Purpose: Grid API Documentation
--
--============================================================================--
