--============ Copyright © 2019, Planimeter, All rights reserved. ============--
--
-- Purpose: Grid API Documentation
--
--============================================================================--
