--============ Copyright © 2020, Planimeter, All rights reserved. ============--
--
-- Purpose: Grid API Documentation
--
--============================================================================--
